### ISSUE TITLE
[Gum] "Relative To Children" layout refresh bug

### ISSUE THREAD

**Issue by Arcnor** [vchelaru/Gum#106]
1. Create `Parent`, `Inner` and `Text` objects, set last one to type `Text`
2. Set a very long text on `Text` object, set "Text Overflow Vertical Mode" to "Truncate Line"
3. Set `Parent` as parent to `Inner`, `Inner` as parent to `Text`.
4. Set `Inner` Width and Height Units to "Relative to Container", then set both Width and Height to 0.
5. Do the same (in the same order) on `Text`
6. Set `Inner` Height Units to "Relative to Children"
7. Do the same on `Text`

Height will still be 0 for `Text` and `Inner` after you do this. If you force a refresh of the layout (by modifying some properties of `Parent` for example) height will be corrected.

**Comment by vchelaru** [comment]
This is causing a problem because there are 2 competing values:

1. The Text's **HeightUnits** is **RelativeToChildren** which means - the children (lines of text) should determine its height
2. The children (lines of text) depend on the Text object, are truncated which means that the height should determine the lines of text.

Which should be dominant?

**Comment by vchelaru** [comment]
Fixed

7f3ab2a07c0611d72030bec2aa46bab082ee24c5
