### ISSUE TITLE
Crash when external texture cannot be opened

### ISSUE THREAD

**Issue by Arcnor** [vchelaru/Gum#112]
Gum should not crash and possibly ask to find the texture somewhere again (but at least not crash :D)

**Comment by vchelaru** [comment]
I have also attempted a 2nd test:

1. Create a Screen
2. Add a Sprite
3. Have the Sprite reference a PNG
4. Shut down Gum
5. Open the PNG in a text editor
6. Add random characters throughout the PNG to corrupt the file
7. Attempt to open the PNG in an application like Paint.NET to verify that the PNG is corrupt
8. Re-pen Gum
9. Select the previously-created Screen

Observe - the Sprite cannot open the texture because it is corrupt, but displays a red X

![image](https://github.com/vchelaru/Gum/assets/729631/a4c8210a-09ef-4fcc-95c2-a6898c25a161)

**Comment by Arcnor** [comment]
My test was just copying the project to a new computer, and it crashed when trying to fetch the texture (not even the directory for it existed), but I can probably try again, will let you know.

**Comment by Arcnor** [comment]
Crash is at https://github.com/vchelaru/Gum/blob/a03ca05a0faf216dd128e218322228741bbea6cb/ToolsUtilities/FileManager.cs#L666

```
System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\...`
```
