### ISSUE TITLE
[Documentation] Adding to Monogame page is broken

### ISSUE THREAD

**Issue by realcoloride** [vchelaru/Gum#123]
Hello,

The following page: http://gumui.net/adding-gum-to-monogame/ is broken and does not display anything.
![image](https://github.com/vchelaru/Gum/assets/108619637/c4311a1e-87ab-4861-ad76-ddaa9e71359d)

**Comment by vchelaru** [comment]
Thank you for making this issue. The MonoGame + Gum steps previously required using the FlatRedBall game engine. There's now a new library that can be used that does not require FlatRedBall, but it requires a bit of manual work to get hooked up. I'm in the process of making it much easier to add to a MonoGame project.

If you're interested in this new process you have a few options:

1. You can wait as I work through to make it easier to add to a game. This may take a week or so.
2. You can help me test early versions and I can help your game get hooked up. I'd be glad to give you help on chat or on screenshare if you'd like to join our discord (it's  a FlatRedBall discord, but it's for Gum users too). 

If you'd like to track progress or get an early build or help test it sooner, feel free to join the discord: https://discord.gg/3gWj3wbC87

Otherwise I'll post progress here.

**Comment by realcoloride** [comment]
Please let me know when the page is up again. I will potentially use it for MonoGame.
Thanks for the answer!

**Comment by vchelaru** [comment]
Lots of progress so far. I have created a sample project in the repo here:

https://github.com/vchelaru/Gum/tree/master/Samples/MonoGameGumInCode

I'm still working on it, but this will give you a quick idea of how it works in code.

**Comment by vchelaru** [comment]
More progress - here's a screenshot of a layout in the Gum tool, and it loaded from-file and drawing in MonoGame

![image](https://github.com/vchelaru/Gum/assets/729631/06d5d759-0f69-46fe-af79-943aca42f17f)

**Comment by vchelaru** [comment]
I still have to fix the main page, but here's the very first doc that shows how to get set up and create a rectangle in code.

https://docs.flatredball.com/gum/monogame/setup

**Comment by vchelaru** [comment]
I'll be working on the main page which still links to the bad page, but in the meantime I believe this issue is complete. Here's a summary of what is done:

* Gum.MonoGame nuget package is now available. This pulls in all other dependencies
* Gum.MonoGame now has a simple set of initialization steps
* Gum.MonoGame can create "Runtime" objects in code allowing for code-only setup of Gum screens and components
* Gum.MonoGame allows for the loading and displaying of Gum projects in their entirety
* Gum.MonoGame now has 2 sample projects - one showing how to load from-file, one showing how to work with Gum in code
* Documentation has been updated to show how to set up a project

The docs were the original point of this card but a lot of work was needed to set this all up. Please check it out and let me know if there are any problems you encounter.

https://docs.flatredball.com/gum/monogame

**Comment by realcoloride** [comment]
Brilliant work. I'll let you know if I need anything.
