### ISSUE TITLE
Auto Grid Vertical uses horizontal layout

### ISSUE THREAD

**Issue by tomcashman** [vchelaru/Gum#160]
We have a sequence of 80x80 sprite instances inside a container. The container is set to Auto Grid Vertical but the elements layout in Auto Grid Horizontal.

![image](https://github.com/vchelaru/Gum/assets/1745420/a867dbe4-b768-4545-81c7-45699dcc8d4e)

**Comment by vchelaru** [comment]
Thank you for reporting this. I will review it soon.

**Comment by vchelaru** [comment]
Fixed in this commit:

fdaa8d56e70e837200c6e570197d9b89a3358f9b

If you are building from source, you can pull latest, build, and run and it will be fixed.

If you are not building from source then I will release a new update this week - I'm out of town currently and I have to do it on my home machine so I can't do it right now.

Let me know if you need help building from source, but if you clone the repository and open the .sln in Visual Studio it should build and run.


![08_09 11 51](https://github.com/vchelaru/Gum/assets/729631/8332c185-2363-48ce-a31e-a4f7a784def8)

**Comment by tomcashman** [comment]
Thanks for the quick fix :-)
