### ISSUE TITLE
Duplicate instances can get created in a Component

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/Gum#185]
I don't have good repro steps for this, but I've seen it happen a few times. Once it happens, sometimes 2 items may show up in the preview window.

This can be solved by removing one of the entries manually from the XML file.

![image](https://github.com/user-attachments/assets/7b59eb3d-7d5e-4673-8ed9-0be0622cd3c9)

Good repro steps would be very much appreciated if anyone knows how to get it to happen.

**Comment by profexorgeek** [comment]
This cannot be solved by removing one of the entries manually from the XML because Gum is continually creating duplicates. In this gif (latest Gum build) I create a new component and start adding items to it. If it matters, the first item I add is copied from another component.

It's not obvious in Gum what's happening but every component in here is being double-created and the errors start stacking with each component:

![gum-duplicates](https://github.com/user-attachments/assets/2e5f56f5-6328-4b00-b31c-4e012128e307)

**Comment by vchelaru** [comment]
fixed
