### ISSUE TITLE
Best practice to create bitmap font map for Gum

### ISSUE THREAD

**Issue by leandrocurioso** [vchelaru/Gum#187]
**Hi guys!**

I'm using Bitmap Font Generator to export my font that is 30px. I noticed that when I load the font in Monogame with Gum it takes quite a while to complete. Is there a good practice to generate this bitmap fonts for Gum?

I think something related to the final .png dependding on the width and height could impact the load time. IDK

Any ideas?

**Comment by vchelaru** [comment]
When you generate with Bitmap Font Generator, you can specify the size of the font. You want to keep the font size as small as possible while still allowing for all characters to fit in 1 png. Of course, this can be problematic if you are storing large character sets, such as Chinese or Japanese. If you are generating them automatically through Gum, then Gum decides on the sizes and these can definitely be improved if you do it manually.

However, even 4096x4096 textures load fairly fast for me.

How many PNGs are in your character set, and how large are each? Are these generated automatically for you by Gum? Or are you doing it manually through Bitmap Font Generator?

**Comment by leandrocurioso** [comment]
I'm using Runtimes, not using the UI tool, the need of bitmap font is that I require to customize the text of my buttons and textboxes placeholders.

I'm generating everything inside the a single .png fie here an example:

https://ibb.co/qMLByhy (Will  appear fully white but the fonts are there  lol)

it's taking about 5-7 seconds to load the font. Maybe this is normal and I did not know.

**Comment by vchelaru** [comment]
@leandrocurioso no, this should load very quickly - definitely less than 1 second. How long does it take to load the PNG as a Texture2D? Is that slow also? That will help us tell if it's the PNG loading that is slow, or if it's another part of Gum.

If you would like to upload a sample project, I can also try it on my machine to see if it takes 5-7 seconds, and if so I can diagnose the problem deeper.

Also, if you would like to chat on Discord that might be faster. I'll be on all day and we might be able to solve the problem quickly. Of course, here is fine too, but the back-and-forth may take longer.

**Comment by leandrocurioso** [comment]
Ok I will prepare the project and enter discord thanks!

**Comment by vchelaru** [comment]
@KallDrexx I've created a test project for you to test this. To reproduce it:

1. Clone the Gum repository (`master` branch)
2. Open <Gum>\Samples\Tests\FntLoading\FntLoading.sln
3. Build and run the app. Wait for a blue screen to show.
4. When the app is running, press the SPACE bar
5. Look at the output window to see information about timing - it may take 5-10 seconds to display

The method in question is SetFontPattern. Note that the method is broken up into a few parts (feel free to refactor those further if you want). 

![image](https://github.com/user-attachments/assets/8b930d05-eb06-4a61-84a2-a092eb6b7619)

Note that the Font is created initially using a much smaller dummy font, but then it's re-assigned in response to space bar. The initial assignment needs to be there because that's a requirement of the font constructor, so if you add timing, you'll want to figure out a way to skip that initial load.
