### ISSUE TITLE
[GUM] Templates

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#210]
Create the ability to have templates that can be used to create a new project from.

If not, perhaps provide a templates section on the documentation site, where users can download pre-made templates.

Suggestions for templates:

Screen management (Start screen, options screen, etc)
Crafter GUI (1, 2, 3, 4, 5, 6, 7, 8, 9, 0) action bar 
HUD for showing Health / Mana / Random Stat
etc

Could also have themes:
perhaps work in some sort of TINT/IMAGE naming convention to the templates, and the themes will replace certain colors/tints/images.

Dark mode
Soft glow
Light mode
etc etc

**Comment by vchelaru** [comment]
Please review brandh `210-gum-templates`

This has changes to the MonoGameGumFormsSample

**Comment by vchelaru** [comment]
After speaking to @kaltinril I now understand what this issue was originally asking for. In the context of MonoGame, common controls such as button, text box, etc can all be implemented more easily using Gum Forms. This process is documented here:

https://docs.flatredball.com/gum/monogame/gum-forms

A sample also exists which shows how to work with Gum Forms with a Gum project (gumx) which is fully customizable. More information here:

https://docs.flatredball.com/gum/monogame/samples#monogamegumformssample

The sample is new since this card was created, as are a lot of the docs. Since we've made lots of progress towards making it easier to have working controls out-of-the-box, I am going to close this issue and if additional work is needed, a new issue should be created with specific enhancements called out.
