### ISSUE TITLE
[GUM] LineHeightMultiplier not defined in TextRuntime

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#230]
Unknown, I just see this error when I try to use this in my test project.

![image](https://github.com/user-attachments/assets/6786cf63-20f1-4036-817e-d3e368bd1117)

**Comment by kaltinril** [comment]
Looks like this is some "Skia" thing?  Why is my Gum.exe including Skia things automatically?

**Comment by vchelaru** [comment]
The LineHeightMultiplier was in fact originally added because it was supported by the Skia runtime for Gum, but this property has since been brought over to MonoGame as well. I forgot to update the TextRuntime to support `LineHeightMultiplier` and also `TextOverflowHorizontalMode`. 

This commit adds these properties. Thanks for spotting this!
6a6a2519e8bcfbdc30e7244e5bb6ca9469782e03
