### ISSUE TITLE
[GUM Tool] Add Grid snapping

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#252]
Allow the ability to add a snap-to-grid option.

Either with a toggle like a checkbox or hotkey.

Or with a held button like CTRL or SHIFT or ALT drag.

Not sure how useful this would be, but was thinking about it when writing up the video about the ruler line click tip

**Comment by vchelaru** [comment]
This is a very complicated feature because it makes sense when you are working with absolutes, but it falls apart when using unit types that do not snap.

Some questions - considerations:

* Would this be just for position? Or also for sizes?
* If snap is enabled and the user changes position values which are relative to center - would the object snap to the world grid, or would it snap to units relative to center? If it snaps to world grid, then changing the size or position of a parent would then un-snap all children potentially. If it snaps to relative coordinates, then objects that use different unit types (left vs middle vs right) would not be snapped to one-another.
* What would happen if using percentage or stacking? 

I think this feature is a good feature in concept, but lots of details need to be worked out first. Let me know if you have thoughts on this.

**Comment by kaltinril** [comment]
Good points @vchelaru Maybe this shouldn't have been an issue/ticket, and I should have just started with a question/thought in Discord, if you want we can close this, it was just a thought/idea.  I do not need this specific feature.

**Comment by vchelaru** [comment]
I do like this feature conceptually, especially for NES-style games where you want to really mimic the way the NES would do its UI with tiles. Setting grid sizes to 8 or 16 would help a lot with that. However, since it is a bit of work, and since there are some edge cases, I think it's best to postpone working on this until someone actually needs it for a game.
