### ISSUE TITLE
BUG: Category Removed from States of a Behavior is not removed from the Components that use it

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#283]
Steps to reproduce:
1. Load up Gum Forms for Monogame
2. Create a new project, save it, etc.
3. Click on ButtonBehavior
4. Right-click on States and add a new category
5. Click on an existing Component like ButtonStandard, notice the new category was added, and also notice no UNDO history.
6. Click on the ButtonBehavior and remove the new State
7. Click back on the Existing Component ButtonStandard and notice the new category remains.

![YYwTueEPxN](https://github.com/user-attachments/assets/0115a1cc-94bd-4c0c-877c-a3cf26caaeea)

**Comment by vchelaru** [comment]
This is technically as designed because a removal of a state from a behavior does not necessarily mean that the state should also be removed from all components that use that behavior. You can think about it like an interface in c#. If you add a new property to an interface, then that property must exist in any class that implements that interface. However if you then remove the property from the interface that does not suggest to visual studio that you should also remove that property from all classes that use that interface. I realize it's not the exact same thing because we're talking about code versus gum, but it would be inappropriate for gum to just assume that you intend to remove all states within that category just because the behavior changed.
