### ISSUE TITLE
BUG: MonoGame codegen missing from drop down

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#290]
After the updates I can't see the Monogame option anymore.

Inheritance location Panel is also missing.

![1xgmAiyaSQ](https://github.com/user-attachments/assets/6ad593dc-2e2e-4dc0-bbd0-eaf09c05f95f)

**Comment by vchelaru** [comment]
This is likely because you are running old plugins. Plugins projects must be built to get the latest, and this doesn't happen if you press F5 to launch the project. You should Built -> Rebuild Solution in Visual Studio, then run Gum. More info here: https://docs.flatredball.com/gum/gum-code-reference/running-from-source#building-plugins
