### ISSUE TITLE
BUG: Multi-select variables display unusable things for all selected components

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#293]
Found a weird bug with color picker on accident. 

1. select mulitple elements in a screen
2. go to color picker
3. multiple undo's will be created, and you can't DRAG the color picker, it sort of hangs and disappears
4. Notice that you shouldn't be able to see color for some things but it shows up anyways

![M1kaLAFTsB](https://github.com/user-attachments/assets/4360960d-21d2-4795-b743-a7d37583a515)

**Comment by vchelaru** [comment]
I've reviewed this and after talking to @profexorgeek , we believe that this should continue to display variables so long as at least one of the objects includes this variable.

I've also made some significant improvements to how multi-editing works. As defined here, the bug is actually not a bug. I know I said that it was on discord, but I've changed my mind after further discussions.
