### ISSUE TITLE
PERFORMANCE: New undo starts to take a toll on the computer

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#296]
After 2+ pages it really starts to get noticeable, and the was me messing with a single component I was creating.

![ldWPhevcqh](https://github.com/user-attachments/assets/1b8f4178-399e-4c6f-8f60-5d970031c85e)

**Comment by kaltinril** [comment]
![Gum_MkiyISRlnD](https://github.com/user-attachments/assets/fc11f531-89b5-49f9-91fd-89415f1ad2a7)

**Comment by kaltinril** [comment]
Steps to reproduce:
1. Add some sort of component
2. add a colored rectangle instance to the component
3. click on all the units to force many undo history items for 2+ pages in the History when your history tab takes up your entire window

![image](https://github.com/user-attachments/assets/aaf19a70-5ab5-4745-aae2-b1a16ef5f5cf)

**Comment by vchelaru** [comment]
I've just pushed another performance improvement and on my end it seems to be running great. 

0d84890f5965780fbdcfab9edbbe823f5017b9f1

Just in case it's still a problem, I'll break down a little bit of the types of work that Gum does for undos so that we can track the problem more precisely.

* Undo-Redo - when an undo/redo works, the entire list is no longer re-constructed. This used to be the case before, and recreating the entire list can be slow when there are hundreds of items. Also, I've made it so that less UI has to be refreshed on an undo. In my experience undo/redo works very fast now 
* Recording new action (adding to end of list) - the last time you tested this, any time a new action was added the entire list was updated. Again, this could get very heavy. The latest version that I just pushed will only append a single item to the list which makes it much faster than before.
* Record new action (middle of list) - if you undo so that you are not at the end of the action list, then perform an action, this wipes all actions that were past the current action (gray text). This should also now be faster as it just deletes the actions, and only appends a single action, just like the previous point
* Selecting a new item - this still requires a full update of the entire list, so this one will still be slow when swapping between different screens and components

Can you please test again and let me know which is slow?

**Comment by vchelaru** [comment]
Verified this fixes the problem
