### ISSUE TITLE
Edit variable is confusing and some broken behavior I think

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#299]
1. When I edit a variable, it shows an "Add Variable" screen. Should show Edit Variable.

2. If I just click Ok to the popup, it defaults to ElementName.VariableName.  However, Period's are not allowed in a Variable name so it gives an error.  First, why suggest or allow someone to type characters that are not allowed?  Second, why isn't the Name the original name before I right-clicked and did Edit?

![LDjJ4MnNY4](https://github.com/user-attachments/assets/3890e299-6527-43b8-b6d5-34d440135e52)

3. If I type in a name, the renamed variable disappears from the exposed variables.
![Po3YVXxvvI](https://github.com/user-attachments/assets/02bf1624-ae2b-49c9-856c-44b9ddd8e5dc)

4. The accidently unexposed variable (from error in step 3) also looses it's value (You've stated that nothing should lose values like this) and it goes back to the default value instead (green). 

![Gum_tPOGOJiTu8](https://github.com/user-attachments/assets/a21b45cf-2352-49a7-ac87-84a617455fb4)

5. Also the variable somehow exists that I renamed but I am unable to see it, nor add a new exposed variable with that same name.

![i5UxwcsMCq](https://github.com/user-attachments/assets/4b054fe4-3d09-42e4-8bcb-f48a16740e8d)

**Comment by kaltinril** [comment]
I ended up causing a crash apparently once I added the instance to a screen to test it, both exposed values for blue bar were showing, one was 111 and one was 255.  I changed the 255 one to 100, and then when I tried to change the 111 one to 50, it crashed.

![image](https://github.com/user-attachments/assets/80b12f19-3959-40b5-937f-983fdba51f5d)


![9bQ7doTZ4E](https://github.com/user-attachments/assets/11ec9ead-a04d-447e-aee6-f540aa00e28e)

**Comment by vchelaru** [comment]
I had to do a little investigation on this because I couldn't remember exactly how this worked. It turns out that editing variables is only intended to work on variables which are not defined by their root standard element save. In other words, you should not be able to edit variables which come from a base standard element such as a NineSlice's Red,Green,Blue values.

You should only be able to edit variables if any of the following are true:
* They are variables defined in a behavior
* They are variables which are added to a component as a pure standalone variable rather than inherited from the base

Both features are still only halfway implemented, so this means that editing variables is effectively not used in common Gum work. 

The fix (for now) is to remove this menu item from any variable that is not in a behavior.

This has been fixed here:

66eac456ddd952dffd37e967c95451708891fa52

**Comment by vchelaru** [comment]
That's a good point. Yes, that is how it has always worked, but...as usual your perspective makes me realize that it shouldn't continue to work this way. I'm going to make a new card and link it here because being able to rename exposed variables is going to be a bit of work to make sure that propagates to all instances. New issue incoming...
