### ISSUE TITLE
Enhancement: Clicking on different instances should make sure they are on the screen

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#300]
**Urgency level:** Super low Priority (Not urgent)

**Issue:**

When I click on different screens or components or standard elements, the Editor view stays in the same X/Y Width/Height Zoom level.

**Suggestion:**
Instead suggest making sure the elements on that thing are displayed in the editor.  This way a user doesn't have to middle click scroll around all the time.

**Options:**
A) Save the state of the X/Y and Zoom per Component/Screen/Standard.
B) Auto calculate the needed zoom level to always encapsulate the entire thing (Find left most item, find right most item, find top most item, find bottom most item, divide by actual width/height to put all elements on the screen at the same time.

![Gum_NGpy1RVPx2](https://github.com/user-attachments/assets/ab4c7f55-dee7-485c-a258-197a7bc4036f)

**Comment by vchelaru** [comment]
Thoughts on this @profexorgeek ?

**Comment by profexorgeek** [comment]
This is a good idea in theory and might be helpful when working on disparate pieces of something like a HUD. However, in the majority of cases it could be extremely disruptive.

Imagine working on a complex menu such as the screenshot below. Every time you click on an element in the tree view, the UI would jump around. This would be extremely annoying when tweaking the alignment and layout of a lot of components in a non-trivial UI. I believe that I specifically requested that Gum (or another FRB tool) _does not_ change the zoom and X/Y when working because it was so disruptive.

**If you do add this feature, make sure you give users the ability to turn it off globally in preferences!**

![image](https://github.com/user-attachments/assets/2223506d-1280-46db-b4ce-d5196271666d)

**Comment by vchelaru** [comment]
Closing
