### ISSUE TITLE
BUG: Deleting a component doesn't delete everything

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#302]
Story mode:
I copied a component, but wanted to make some more changes to both the original and copy.  Since I had not yet changed the new component, I simply deleted it, made the changes to the original component, and duplicated it again.  I got an error that a file already exists.

I looked in the folder and sure enough, some sort of "animation" file even though I don't have any animations that I am aware of.

After deleting the component a 2nd time, and then the file, I was able to correctly Duplicate the Component without and error.

Steps to reproduce:
1. Create a component
2. Do whatever Gum requires so that it generates a "ComponentNameAnimations.ganx" file.
3. Duplicate the component
4. Delete the duplicated component created in step 3
5. Duplicate the component a second time
6. Now you get the error that the Animations file already exists.

![explorer_aMea8gpDX7](https://github.com/user-attachments/assets/7939690e-6762-4b5c-93cd-e7764f1965cb)

**Comment by vchelaru** [comment]
Now when a component is deleted, animation file presence is checked. If a file exists, then the popup asks if the animation file should be deleted too:

![image](https://github.com/user-attachments/assets/8e84157b-0bc3-43e3-ab87-516a95f716df)

Also, if you duplicate an object you now get a more informative message about copying files over instead of a long error message.
