### ISSUE TITLE
States and Categories confusing

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#311]
I was a bit confused when I was working on a script for my states and categories video.

1. I created a screen
2. I added a ColoredRectangle instance to the screen
3. I clicked on the ColoredRectangleInstance
4. I then added 2 categories (Color, Rotation)
5. I added 3 states to color (Red, Green, Blue) and 2 states to Rotation (Normal, FourtyFive)
6. I then tried to "Set" the state and realized I couldn't find it.  I kept looking and did not see a way to do this.

THis... I realized....  The state and Categories were attached to the SCREEN and not to the INSTANCE.

This is not obvious or apparent at all to a new person.  It would appear I need to create a Component if I want to use States and Categories, which again, is not visually understanding.  The Column of properties like Variables, Behavior, Alignment, and States I "assumed" belonged to whatever I had selected.  I did not realize the States belonged to the Screen or Component level. 

This feels like hidden behavior or unexpected behavior.

![image](https://github.com/user-attachments/assets/e6fbd923-f810-49cb-9679-556ebb268664)

**Comment by kaltinril** [comment]
So I guess my poposal would be change the States tab to be named

"ObjectName States"

Example:

A screen called "TitleScreen" would make the States tab read "TitleScreen States"
A component called "MyFancyThing" would make the States tab read "MyFanceThin States"

While this doesn't 100% auto-document it, I think it helps someone reviewing the page to understand what the states belong to.

![image](https://github.com/user-attachments/assets/e6e03454-672c-4c2a-a7ac-aa836d604e93)

**Comment by kaltinril** [comment]
Sorry, I spent about 1-2 hours and I can not figure out how the heck to change that tab when a treeview node is selected....  The spiderweb connectivity or UI code is a bit much for a project this large for me to try to find it.

I was able to find `OnSelect` in the `ElementTreeViewManager.cs` which appears to trigger whenever I click on the Folders, "Element" (Root item under the folder) or an Instance.  However, I can't figure out how the States Tab is refreshed I don't see any calls.  So I can only assume it's the UI Magic of binding things with "hidden" functionality that C# encourages.

I also traced the call tree back up, but was unable to find anything that forcefully told the States tab of treeview to update.
MultiSelectTreeView.cs -> OnMouseUp()
 -> MultiSelectTreeView.cs -> AfterClickSelect(this, new TreeViewEventArgs(node)); [Line 263]
  -> -> ElementTreeViewManager.cs -> ObjectTreeView_AfterClickSelect
  -> -> -> ElementTreeViewManager.Self.OnSelect(ObjectTreeView.SelectedNode);

I also tried to work from the MainWindow.cs file down, but lost it after line 75 and 76.

I was hoping I could put something in OnSelect that would find the root "Element" in the folder, and then do a simple `Gum.Controls.StateView.Text` or `GumCommands.Self.GuiCommands.FindControl("States")` or something....

**Comment by vchelaru** [comment]
Thanks for the suggestion and I apologize for the frustration of finding the code. First let me say that the State tab code is not following the standard pattern of code in Gum, so I also had some problems tracking it down. That said, I refactored the code so that it follows the standard plugin system in Gum.

If you're curious, I'll briefly explain the architecture in case you do want to browse through code or make changes in the future.

Gum is built around a plugin system facilitated by MEF (Microsoft Extension Framework). The details of MEF probably don't matter too much, but here's the general idea:

Gum itself is an application which is (increasingly) limited in functionality. More and more functionality is moving out of Gum and into plugins. Plugins (for the most part) do not reference any code from each other, but instead just work directly with the core Gum system. The most obvious thing that a plugin can do is add tabs to Gum. For example, the States tab is now handled by the MainStatePlugin.

Plugins can be _internal_ or _external_. Internal plugins are required for the regular use of Gum (such as the States tab), but they still exist as plugins for the sake of organization. External plugins can be considered optional and are not required for the full behavior of Gum. At times, plugins (such as the Code tab plugin) are created as an experiment or only useful in certain rare cases, but they may evolve over time to become more important in common usage.

Plugins have a StartUp method where they can initialize things that will always be available - such as adding a tab or subscribing to events. Plugins also have a large number of events that they can subscribe to for situations like when a user selects a new item in the tree view.

In the case of the State plugin, the tab is created on StartUp, and an event is subscribed for whenever a treeview is selected to update the tab's title.

If you're interested in getting deeper into plugins I'd be happy to provide more details. Otherwise, you can look at the commit that resolves this issue to see how I migrated code into the plugin, and to see how the tab is updated upon selection.

**Comment by vchelaru** [comment]
Fixed by 52103c151c150681b7d228328e68f45408422b48

**Comment by kaltinril** [comment]
I just looked at your "overhaul" and was shocked there were only like 20 lines changed...  I do not see how the new state has access to the treeview from the other area that's confusing.  I tested it and it worked though, I also didn't understand how the Element was already correctly the PARENT/ROOT name, nice work !

**Comment by vchelaru** [comment]
I'll reopen this as a reminder to answer your questions

**Comment by kaltinril** [comment]
You don't have to leave it open.

Maybe this weekend or something you can give me a high level rundown.

Your changes worked.

**Comment by kaltinril** [comment]
You did a high level overview of stuff with me and you can close this out if you'd like.
