### ISSUE TITLE
Research/document different texture address mode wrapping on sprite

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/Gum#326]
@kaltinril  asks:
> And also, why doesn't wrap do anything for the other texture address options on sprite?

**Comment by kaltinril** [comment]
For a sprite's Texture Address.

**EntireTexture:** Does nothing
https://github.com/user-attachments/assets/2299a5e4-a1fe-46c6-96c0-38c92c009208

**Custom:** 
1. Bug at first, doesn't show until you click off the instance and back onto the instance.
2. Changing the texture size doesn't do anything
3. Can use the Left, Top, Width, Height to "pick out" a texture
4. No wrapping occurs

**DimensionsBased:**
1. Display suggestion.  Show at % instead of showing as decimal.  Users do not want to do math or think about that.  Or, at least tell them it's a percent somehow so they realize the 1 doesn't mean 1 pixel like all the other values do.
2. This is the only WRAP that does tiling it appears when Wrap is checked.
3. When unchecked it just replicates the last pixel at the edge (right/bottom)


![image](https://github.com/user-attachments/assets/b9a76bb9-2305-4fa0-b4dd-28d23e752437)
![image](https://github.com/user-attachments/assets/f0b8b1f0-4a4f-4b40-aee6-a2f34ff1d48e)

**Comment by vchelaru** [comment]
Logging additional issues here as I work on them:

- [ ] Double-click in Texture Coordinates tab is not updating the texture coordinates values in the Variables tab

**Comment by vchelaru** [comment]
Tons of new documentation on wrap here:

https://docs.flatredball.com/gum/readme/gum-elements/sprite/wrap
