### ISSUE TITLE
(Low) right-click to expose variables - Missing locations

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#345]
As a user I should not have to right-click exactly on the value/textbox/icon/label.  I should be able to right-click on any part of the variable to Expose the variable as well.

Since there is a work-around (Users can just right-click on the other aspect like the textbox) I would consider this is low priority.  If you direct me on where to start looking for this, I can go make all the changes, I imagine this is small.

1. Rotation (Textbox/value) This is the opposite, I can right-click on the Label and Wheel, but right-clicking on the Value does not let me expose variable.  Rotation Label SHOULD allow right-click to Expose Variable
![image](https://github.com/user-attachments/assets/7342f48f-2693-4665-b460-ac89d18b89b4)

2. Source File - NineSlice and Sprite - Label should allow right-click to Expose Variable

3. Component Definition - Children - Children Layout - (Label and Icons) - Right-click should allow me to Expose Variable
 (NOTE: This does work on Container Instances and Component instances though)
https://github.com/user-attachments/assets/f2358713-dded-4776-a571-a585bcf95288

4. Component Definition - Children - Clips Children - (Label and checkbox) - Right-click should allow me to Expose Variable
 (NOTE: This does work on Container Instances and Component instances though)

5. Text - Font - Font - (Dropdown) - Right-click should allow me to Expose Variable
![image](https://github.com/user-attachments/assets/8a4da2e9-8b74-48a6-ac69-8ab8bbcb42dc)

**Comment by kaltinril** [comment]
@vchelaru  I can try to tackle this one, but I can NOT figure out where the right-click menu functionality lives for these variables??

If you guide me I could probably do this one.

**Comment by vchelaru** [comment]
I will provide some information here and fix the angle context menu. I'll leave the others to you since you said you wanted to try tackling it.

The right-click menu is called a ContextMenu in WPF. Different controls (such as a text box and the entire grid that contains the label and the text box) can have different context menus. This is evident in the angle selector because you get different context menus when you right click on different spots.

Gum has logic for populating the context menu, so long as it knows **which** context menu to populate. I'll avoid going into too much detail here, but ultimately this happens in the IDataUiExtensionMethods RefreshContextMenu method.

We need to make sure that all context menus get updated. For example, notice that multiple context menus are updated here:

https://github.com/vchelaru/Gum/blob/8a3c1f9536fd38023e517194e4266b92020af856/WpfDataUi/Controls/TextBoxDisplay.xaml.cs#L146

We need to do the same thing in the controls where right clicking is not working. Note that to access the menu we must explicitly add one to the Text box. See the this commit for an example:

e6dfda6f2959bd802cb80522c5aecbbee7d033d4

**Comment by kaltinril** [comment]
Sending a PR for 1 and 4, I couldn't find the "Children Layout" button control?

**Comment by kaltinril** [comment]
Doesn't appear I have permissions

Going to create a fork and branch and pr instead

![image](https://github.com/user-attachments/assets/18206c5b-6246-4aa1-ac7f-65df543a4942)

**Comment by vchelaru** [comment]
I believe this is fixed, but I want to make sure about a few things you said above:

> Component Definition - Children - Children Layout - (Label and Icons) - Right-click should allow me to Expose Variable
(NOTE: This does work on Container Instances and Component instances though)

> Component Definition - Children - Clips Children - (Label and checkbox) - Right-click should allow me to Expose Variable
(NOTE: This does work on Container Instances and Component instances though)

Exposing variables is a feature that allows you to take a variable that exists on an instance and make the variable available at the component level. For example, if you have a Button component, you can expose the TextInstance.Text variable which is inside of the Button, and which is normally "hidden" on Button instances.

If a variable is already on the component, then it is already available on instances of the component, so exposing it would not do anything. Therefore, the option to expose should only appear on instances and not on the component definition itself.

Does this resolve all issues?

**Comment by kaltinril** [comment]
Ah OK so it's already "exposed" no need to expose it.

**Comment by kaltinril** [comment]
> Does this resolve all issues?

It does
