### ISSUE TITLE
BUG: Adding child or parent instance should NOT cause Gum Error

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#355]
I was testing the fixes from last night and found a new issue on two different right-click options.

NOTE: I don't know what a child or parent instance is, nor do I know what adding an instance does in the first place.  Documentation for Behaviors is incomplete.

Steps to reproduce:
1. Create a behavior
2. Drag a Standard Text onto the behavior
3. Right-click the Standard TextInstance created in step 3/
4. Both of the following options crash my GUM, and they should NOT crash it:
5. Click either "Add child object to 'TextInstance'"
6. Or click "Add parent object to 'TextInstance'"
7. Enter a name for the "new" object and press enter or click Ok
8. The error occurs

Error:
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'

elementSave was null.
```

Line 271 of NameVerifier.cs

```csharp
var instance = elementSave.Instances.FirstOrDefault(item => item != objectToIgnore && item.Name == name);
```

https://github.com/user-attachments/assets/fc0bb806-2187-4a73-9f33-46ba9c2b6977

**Comment by vchelaru** [comment]
Thank you for spotting this. I admit I only tried a few menu items when I was working on the right-click menu on instances in behavior - specifically **Delete** because that was called out as causing errors in a previous issue. 

The items mentioned here should actually not even show up on instances inside behaviors so I removed them.

I will review the Behaviors documentation.

**Comment by vchelaru** [comment]
Actually I just created https://github.com/vchelaru/Gum/issues/365 for behavior documentation.
