### ISSUE TITLE
Sprite wrapping

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#389]
When I have WRAP selected for "Custom", and Width/Height units are set to "Percent of File".

I do not understand why Custom will stretch the image if I change the Sprite's width/height in the editor

but....

If I change the Texture Width and Texture Height under Source, the sprite's width and height change, yet it wraps this time.

But...

If I select "Absolute" for the Width/Height, and then adjust the Texture Width and Texture Height, it keeps the same editor dimensions, but stars to tile/wrap and progressively the wrapped image gets smaller and smaller.

However...

If I simply change the Heigh/Width without touching the Texture width/height (Same behavior where it just stretches the image)

This feels like odd functionality

https://github.com/user-attachments/assets/38f4edb7-25f0-4e0c-81a3-92094c35c98a

**Comment by vchelaru** [comment]
I'll try to break down each part to explain what is happening:

> I do not understand why Custom will stretch the image if I change the Sprite's width/height in the editor

When you use Custom, then the texture coordinates are explicitly set. They do not depend on the dimensions of the Sprite. 

Therefore, when you change the sprite's width and height, the Texture Width and Texture Height remain the same as they were before, but the same values must now be shown over a larger area (if you make the Sprite bigger). Therefore it stretches. Wrap has nothing to do with it, whether you wrap or not the texture coordinates are still fixed, and changing the Sprite size will stretch/shrink the shown portion of the texture.

> but....
> If I change the Texture Width and Texture Height under Source, the sprite's width and height change, yet it wraps this time.

By changing the texture width and texture height, you are doing 2 things:

1. You are changing the region of the texture that you are displaying, resulting in wrapping.
2. Since the sprite's width and height are basesd on the source, by changing the texture addresses you are changing the source so the Sprite updates in response.

Remember, with this configuration your effective width is:

ActualWidth = TextureWidth * Width;

By changing either the width percent you increase the actual width, or by changing the texture width you increase the actual width. Wrapping only depends on texture width.


> But...
> If I select "Absolute" for the Width/Height, and then adjust the Texture Width and Texture Height, it keeps the same editor dimensions, but stars to tile/wrap and progressively the wrapped image gets smaller and smaller.

As expected. When you set width units to actual width, the formula becomes:

ActualWidth = Width;

Notice that TextureWidth no longer affects the size of the sprite, but it does affect the wrapping.

> If I simply change the Heigh/Width without touching the Texture width/height (Same behavior where it just stretches the image)

Yes, same as above. By changing width, you adjust actual width, but you do not affect the texture width or height in anyway.

> This feels like odd functionality

The rules are consistent, but they can take some time to wrap your head around them. The way the rules interact is both the source of Gum's flexibility but it also makes it hard to understand. 

This complexity issue exists for lots of things, not just texture coordinates. The Alignment tab is an example of one way that we've tried to make this easier to work with, but I'm not sure how to do so with texture coordinates. I'd def like to chat about this more if you have ideas.
