### ISSUE TITLE
Polygon - Deleting points should update the Editor window

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#403]
If you delete points from the Points listview, it doesn't update the Editor window.

Steps to reproduce:
1. Create a component
2. Drag a polygon on
3. Click on a Point in the Points listview
4. Press Delete
5. The point will be deleted from the list
6. The Editor will not be updated (This is broken)

https://github.com/user-attachments/assets/5d88acb8-e810-4259-9a4d-32f0a3774c19

**Comment by vchelaru** [comment]
This seems to be happening because the `LastOldValue` assignment in StateReferencingInstanceMember is assignd to a reference of the list which gets updated, causing the later logic to identify the value as having not changed. Need to figure out where the reference is shared and clone it. The weird thing is that GetValueOnUi does return a clone so I thought this would prevent reference sharing.

**Comment by vchelaru** [comment]
Fixed by 857c6428b8277cede951a47ceb46a49651039ffa

**Comment by kaltinril** [comment]
Confirmed, fixed.
