### ISSUE TITLE
Gum should not offer to move files

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/Gum#70]
When choosing a source file, gum should not offer to move/copy files that are not at the same file structure level as Gum. Justification:

- If the file is moved it could break other dependencies.
- If the file is copied it could cause hard-to-solve bugs where textures seemingly don't update because they are duplicated.
- If the file is moved or copied it could break its own references, such as an ACHX texture path no longer being accurate.
- The most frequent use case is that the content author is choosing files purposefully and decisively. Forcing them to constantly make the right selection is unnecessary cognitive overhead.
- Moving content should be part of a more purposeful refactor because it's harder to resolve and less safe than a code refactor.
- This is defensive coding against a use case that _might_ happen at the cost of a use case that _does_ happen.

For anecdotal reference I have probably clicked this dialog 1000 times and have never wanted Gum to move or copy a file for me a single time.

**Comment by vchelaru** [comment]
There are 2 common situations when Gum asks you to move a file:

1. You have a file which is WAY outside of the folder structure of Gum. For example, you download a file to the Download folder, or you are grabbing a file which is sitting in some other game project. In this case, the copy behavior is probably a good idea - otherwise you have a gum project (and game) which is not portable at all. The file won't get checked in to your Git repo, and if you copy the project to dropbox or another machine, it will not work correctly. In this case, Gum should probably ask you.
2. You have a file which is sitting inside of a Glue game project, but the file is not within the Gum folder structure. For example, you have a UI sprite sheet which you have sitting in some folder of your choosing in the Content of your game, but the .gumx file is not a parent of that. In that case, Gum should NOT copy the file - you have your game set up the way you want it, and if it copied it, it would be very problematic.

This can be solved by giving the .gumx context of your project. This behavior already exists in .achx files for the AnimationEditor, so it makes sense for Gum to understand "this is the context of your project, so don't ask about anything relative to C:/XXXX".

This value can be set by the Glue plugin on the .gumx file, and once it does, it will eliminate almost all cases where the user should not be asked.

**Comment by vchelaru** [comment]
Fixed.
44c4a103245b785d45c88a13f487ab4a64ff6d01
